### ISSUE TITLE
Dynamic timeout interval

### ISSUE THREAD

**Issue by lmnrg** [DismissedGuy/wiimmfi-rpc#10]
Currently the timeout interval is 15 seconds. That's enough for switching between statuses like "In Menu" and "In a Match".

However, when the user is idle, they're making unnecessary requests to the server, especially if the program is running overnight on their PC, which would stress the server if there are many people using it at the same time.

Maybe you should add a dynamic timeout interval where it slowly increases the timeout interval all the way to 30 seconds when the user goes idle, and after like 2 hours it should increase to 45 seconds and after 4 hours increase it to 60 seconds, etc.

Just a suggestion, and you don't really have to do it. Completely optional, but in case they don't make an API to make this easy to do, and Wiimmfi's traffic explodes, AFK users who use this program wouldn't cause a big problem.

**Comment by malmeloo** [comment]
This feature has been added to prerelease: #14.
It will be added to the next release, but you can already download the bundled binary from the artifacts of BUILD-32452311. Click on the job with your OS and architecture (Visual Studio 2013 = Windows) and then go to the "Artifacts" tab to download the correct zip.

**Comment by lmnrg** [comment]
:+1: Appreciated!
