### ISSUE TITLE
Handle failed pypresence handshake when Discord client is not running

### ISSUE THREAD

**Issue by Clutz450** [DismissedGuy/wiimmfi-rpc#12]
Sorry to create an issue like this but I couldn't find any other place like a help thread forum or similar to ask for help.  I would really like to try this out and under features in the readme it basically says "Download, Unzip, and Go".  So I downloaded the latest release and when I click on the executable file I get an error that says;

"------------ [EXCEPTION RAPPORT AT Mon Apr 20 06:41:33 2020] ------------
  File "C:\projects\wiimmfi-rpc\rpcgui.py", line 164, in <module>
  File "C:\projects\wiimmfi-rpc\rpcgui.py", line 130, in __init__
  File "C:\projects\wiimmfi-rpc\util\wiimmfi.py", line 140, in __init__
  File "C:\Python36-x64\lib\site-packages\pypresence\presence.py", line 40, in connect
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 468, in run_until_complete
  File "C:\Python36-x64\lib\site-packages\pypresence\baseclient.py", line 110, in handshake

----- [PROGRAM INFO]
Bundled: True
----- [DIRECTORY STRUCTURE]
data\friend_codes.json
data\preferences.json
data\statuses.json
data\version_info.json
logs\20200420.log
logs\errors\20200420.log
Wiimmfi-RPC v1.4.0a.exe"

And the other log file says;

"[06:41:32] MainThread INFO: Starting...
[06:41:33] MainThread INFO: Debug mode: ON
[06:41:33] MainThread INFO: Loaded config files
[06:41:33] MainThread DEBUG: Using proactor: IocpProactor"

Would you be able to include a more detailed installation instructions in the readme so I can get this working?  Thank you.

**Comment by malmeloo** [comment]
Hi! Looks like it's failing to pull off a handshake with the Discord client, can you check to see if the client is running on your computer?

I labeled it as a bug since it should be handling these kind of errors instead of simply exiting.

**Comment by Clutz450** [comment]
You know, I didnt even think to have Discord running in the background when I started it.  I'll try that now and report back.

**Comment by malmeloo** [comment]
By the way, I'm currently still working on a more detailed README. You seem to have installed it correctly however, so this is an issue on my side.

**Comment by Clutz450** [comment]
Thank you.  Starting Discord first and then running your program made it start up without error this time.  Thank you,

**Comment by malmeloo** [comment]
This feature has been added to prerelease: #14.
It will be added to the next release, but you can already download the bundled binary from the artifacts of BUILD-32452311. Click on the job with your OS and architecture (Visual Studio 2013 = Windows) and then go to the "Artifacts" tab to download the correct zip.
