### ISSUE TITLE
Which friend code do i enter?

### ISSUE THREAD

**Issue by dogerizergaming** [DismissedGuy/wiimmfi-rpc#15]
Mario Kart Wii Friend Code or Wii freind code?

**Comment by malmeloo** [comment]
Hi! I'm sorry for taking so long to reply, I didn't see your issue.

You're supposed to enter the friend code of the game you want to add, so Mario Kart Wii in your case. For the Game ID field, you should enter the game's ID, but you can also search for your game by typing in that same field. (Hint: it's RMCJ for Mario Kart Wii)

I hope that answers your question, feel free to ask if you need more help.
