### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Oxygemo** [DismissedGuy/wiimmfi-rpc#4]
Make a variable for the Friend Code

**Comment by yeah-its-gloria** [comment]
... why tho?

**Comment by malmeloo** [comment]
What kind of variable do you mean?

**Comment by yeah-its-gloria** [comment]
I guess a variable inside the main program

**Comment by yeah-its-gloria** [comment]
@Alej0hio you can enter your friendcode(s) into the "friend_codes.json" file.

**Comment by malmeloo** [comment]
In case you were wondering, on every start of the program `friend_codes` contains a dict of all the ID/code combinations

**Comment by malmeloo** [comment]
And as this issue has been dead for 2 weeks now, I'm just gonna assume that you indeed meant that variable and your question has been answered now.

**Comment by Oxygemo** [comment]
u
